package mx.unam.ciencias.is.modelo;
// Generated Feb 28, 2018 11:51:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private String nombre;
     private String apellido;
     private Set trabajars = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, String nombre, String apellido) {
        this.empleadoId = empleadoId;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Empleado(int empleadoId, String nombre, String apellido, Set trabajars) {
       this.empleadoId = empleadoId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.trabajars = trabajars;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getTrabajars() {
        return this.trabajars;
    }
    
    public void setTrabajars(Set trabajars) {
        this.trabajars = trabajars;
    }




}


