package mx.unam.ciencias.is.modelo;
// Generated 06-mar-2018 0:19:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private String nombre;
     private String apellido;
     private String correo;
     private String contrasenia;
     private Set trabajars = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, String nombre, String apellido, String correo, String contrasenia) {
        this.empleadoId = empleadoId;
        this.nombre = nombre;
        this.apellido = apellido;
        this.correo = correo;
        this.contrasenia = contrasenia;
    }
    public Empleado(int empleadoId, String nombre, String apellido, String correo, String contrasenia, Set trabajars) {
       this.empleadoId = empleadoId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.trabajars = trabajars;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set getTrabajars() {
        return this.trabajars;
    }
    
    public void setTrabajars(Set trabajars) {
        this.trabajars = trabajars;
    }




}


