package mx.unam.ciencias.is.modelo;
// Generated Feb 28, 2018 10:26:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int proyectoId;
     private String nombre;
     private Set empleados = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(int proyectoId, String nombre) {
        this.proyectoId = proyectoId;
        this.nombre = nombre;
    }
    public Proyecto(int proyectoId, String nombre, Set empleados) {
       this.proyectoId = proyectoId;
       this.nombre = nombre;
       this.empleados = empleados;
    }
   
    public int getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(int proyectoId) {
        this.proyectoId = proyectoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


