package mx.unam.ciencias.is.modelo;
// Generated 06-mar-2018 0:19:22 by Hibernate Tools 4.3.1



/**
 * Trabajar generated by hbm2java
 */
public class Trabajar  implements java.io.Serializable {


     private int idtrabajar;
     private Empleado empleado;
     private Proyecto proyecto;

    public Trabajar() {
    }

    public Trabajar(int idtrabajar, Empleado empleado, Proyecto proyecto) {
       this.idtrabajar = idtrabajar;
       this.empleado = empleado;
       this.proyecto = proyecto;
    }
   
    public int getIdtrabajar() {
        return this.idtrabajar;
    }
    
    public void setIdtrabajar(int idtrabajar) {
        this.idtrabajar = idtrabajar;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }




}


